# This is a basic workflow to help you get started with Actions

name: Feature Branch Workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [feature/**]
    # Only trigger a workflow when changes have been made to files in the below mentioned path.
    #paths:
    #  - "force-app/**"
env:
  SF_QA_ORG__AUTH_URL: ${{ secrets.SF_QA_ORG__AUTH_URL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Validate_To_QA:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #Choose the docker image from which the container should be created
    container:
      image: abhisheksaxena7/sfdx-git-delta:latest
      options: --user 0:0 --privileged
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Authorize Org
        run: |
          echo $SF_QA_ORG__AUTH_URL > authURLFile
          sfdx force:auth:sfdxurl:store -f authURLFile -s -a QA
      - name: Install different git diff plugins
        run: |
          echo y | sfdx plugins:install sfdx-git-delta
          echo y | sfdx plugins:install sfdx-git-packager
          echo y | sfdx plugins:install sfpowerkit
          echo y | sfdx plugins:install dxb@latest
      - name: Diff package from sfdx-git-delta
        run: |
          sfdx sgd:source:delta --from $(git describe --match "qa-*" --abbrev=0 --tags HEAD) --to HEAD --output . --ignore .forceignore
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "qa-*" --abbrev=0 --tags HEAD)---"
          cat package/package.xml
      - name: Diff package from sfpowerkit
        run: |
          sfdx sfpowerkit:project:diff --revisionfrom $(git describe --match "qa-*" --abbrev=0 --tags HEAD) --revisionto HEAD --output sfpowerkit
          cd sfpowerkit
          sfdx force:source:convert -d src
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "qa-*" --abbrev=0 --tags HEAD)---"
          cat src/package.xml
          cd ..
      - name: Diff package from DXB
        run: |
          sfdx dxb:source:delta -m HEAD -k $(git describe --match "qa-*" --abbrev=0 --tags HEAD) -p delta_manifest
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "qa-*" --abbrev=0 --tags HEAD)---"
          cat delta-manifest/package.xml
      - name: Diff package from sfdx-git-packager
        run: |
          sfdx git:package --targetref $(git describe --match "qa-*" --abbrev=0 --tags HEAD) --sourceref HEAD --outputdir git-packager --force --purge
          echo "--- package.xml generated with added and modified metadata from $(git describe --match "qa-*" --abbrev=0 --tags HEAD)---"
          cat git-packager/package.xml
